### ISSUE TITLE
Support mermaid in default templates

### ISSUE THREAD

**Issue by mryhryki** [mryhryki/markdown-preview#74]
## TODO

- [x] Support mermaid in [templates](https://github.com/mryhryki/markdown-preview/tree/main/template)
- [x] Update demo GIF
- [x] Publish to npmjs.com

## Links

- [Mermaid | Diagramming and charting tool](https://mermaid.js.org/)
- [Usage | Mermaid](https://mermaid.js.org/config/usage.html#example-of-a-marked-renderer)
- [Creating diagrams - GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams)

**Comment by mryhryki** [comment]
## Mermaid Example

```txt
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

**Comment by mryhryki** [comment]
## Demo Video

https://github.com/mryhryki/markdown-preview/assets/12733897/868e8fb3-f54c-443a-88f4-752e30c90782
